language: emacs-lisp
jobs:
  include:
    - &test
      stage: test
      os: linux
      sudo: required
      env:
        - EMACS_VERSION=26.1
      allow_failures:
        - env: EMACS_VERSION=git-snapshot
      before_script:
        - export PATH=${TRAVIS_BUILD_DIR}/.evm/bin:${PATH}
        - if [[ ${EMACS_VERSION} = git-snapshot ]]; then sudo apt-get install texinfo; fi
        - git clone https://github.com/ubolonton/evm ${TRAVIS_BUILD_DIR}/.evm
        - evm config path /tmp
        - evm install emacs-${EMACS_VERSION} --use --skip
      script:
        - cd $TRAVIS_BUILD_DIR
        - make
        - make test
    - <<: *test
      env:
        - EMACS_VERSION=git-snapshot
    # - stage: deploy
    #   if: tag IS present
    #   os: osx
    #   addons:
    #     homebrew:
    #       packages:
    #         - mingw-w64
    #       update: true
    #   deploy:
    #     provider: releases
    #     api_key:
    #       secure: UHzyKX94UhXQFF+7/ZZIoacQmf3iDmoAGm0bFQ1nunxj5cBTmuN36HrQY+2yxEM5R7xrwLEeK0fmQ5XJyGyuVjb1c0js09mIS1VTVe8U/baF6V4csk/m0ZmQfjSEzxEMmbB7PnfCgsy3aoie7q1OHIqK91v88BNSOCkEHUJzBeOvHCMFLSKKRs2kookdURsGqO6qj8crtYpFBz4Y9D+UELcyeGpQlKPsED35BJ8bqjzh5PnbyuFfXZz958FkD/olvW/27p3TGRp0NwX6kFY9rXTlp8x3pVe10QEHyhfKRhl9PsfvMINB8sc6UdLJYIztfZ47NhjYSB9Z8PF9hpxHrygXbY7+t0iyAIMmXQtr+IeV8bZegITYfLOJrx1noABqVbF2pMjL1uA+lZ6GXGaIbuWS4Du9ex+FCHAq0nM4iOY2g4p8ZAr1Pw81vukGYtmgb4Unyf0tAvgiuQ3INxaqTT3lrmdLrd9eSYnhD6241E5pVMocYfzjZoHUzu0mB8wXKHstPi6jT0L7r1CwyTQRp8iMX3pKSmMTMfDTIn71E4A7hczq6DL+cHUyenmVWSXemSvnKUE2No3IXLCxt7th9Ur8MYfpdKnl9whyOD3TVbz1qmondDwHvfemp/NsAT/80D+wlKAYYKWdxLoN5jWGLa9i+2i26nczwvgolTQystw=
    #     file_glob: true
    #     file: products/*
    #     skip_cleanup: true
    #     overwrite: true
    #     on:
    #       tags: true
    #   env:
    #     - ZMQ_BUILD_HOST=x86_64-w64-mingw32
    #   script:
    #     - cd $TRAVIS_BUILD_DIR
    #     - make products
